{% set version = "0.3.1" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 029903176e3090d2d69713a4320629396a2c36a32922fbdac21d4d6d9fdd17cb

build:
  number: 0
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: "python setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - msgpack-python
    - msgpack-numpy
    - requests
    - tornado >=4.5.1
    - jinja2
    - ruamel_yaml >=0.15.0
    - dask >=0.17.0
    - python-snappy
    - appdirs
    - holoviews
    - pandas

test:
  source_files:
    - intake
  requires:
    - pytest
    - pytest-cov
    - coverage
  imports:
    - intake
    - intake.auth
    - intake.auth.tests
    - intake.catalog
    - intake.catalog.tests
    - intake.cli
    - intake.cli.client
    - intake.cli.client.tests
    - intake.cli.server
    - intake.cli.server.tests
    - intake.container
    - intake.gui
    - intake.source
    - intake.source.tests
    - intake.tests
  commands:
    - intake list -h
    - intake-server -h
    - py.test --pyargs -v intake

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
