{% set name = "intake" %}
{% set version = "2.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intake-{{ version }}.tar.gz
  sha256: 731d484a002de2f659bb988f406b35037234a35c17b08776d9a5e4838ecf2769

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python
    - pyyaml
    - fsspec >=2023.0.0
    - platformdirs
    - networkx
    # Used here(https://github.com/intake/intake/blob/2.0.8/intake/interface/__init__.py#L7)
    - packaging

test:
  imports:
    - intake
    - intake.catalog
    - intake.catalog.base
    - intake.catalog.local
    - intake.catalog.utils
    - intake.catalog.zarr
    - intake.config
    - intake.interface.base
    - intake.interface.catalog.add
    - intake.interface.catalog.search
    - intake.interface.source
    - intake.readers
    - intake.readers.catalogs
    - intake.readers.convert
    - intake.readers.datatypes
    - intake.readers.entry
    - intake.readers.examples
    - intake.readers.importlist
    - intake.readers.metadata
    - intake.readers.mixins
    - intake.readers.output
    - intake.readers.readers
    - intake.readers.search
    - intake.readers.transform
    - intake.readers.user_parameters
    - intake.readers.utils
    - intake.source
    - intake.source.base
    - intake.source.csv
    - intake.source.derived
    - intake.source.discovery
    - intake.source.jsonfiles
    - intake.source.textfiles
    - intake.source.zarr
    - intake.util_tests
    - intake.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip
    - panel

about:
  home: https://github.com/intake/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system
  description: |
    Intake is a lightweight set of tools for loading and sharing data in data science projects. Intake helps you:
    * Load data from a variety of formats (see the current list of known plugins) into containers you already know, like Pandas dataframes, Python lists, NumPy arrays, and more.
    * Convert boilerplate data loading code into reusable Intake plugins.
    * Describe data sets in catalog files for easy reuse and sharing between projects and with others.
    * Share catalog information (and data sets) over the network with the Intake server.
  dev_url: https://github.com/intake/intake
  doc_url: https://intake.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
