{% set version = "0.6.4" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 468d8083c873d3942be4efc0af6eb42077f091942182bd5cf9209e9d2e7636a7

build:
  number: 0
  noarch: python
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - appdirs
    - entrypoints
    - jinja2
    - pyyaml
    - dask
    - fsspec >=0.7.4
   # extra_require - server
    - requests
    - msgpack-python
    - python-snappy
    - tornado

test:
  source_files:
    - intake
  imports:
    - intake
    - intake.auth
    - intake.catalog
    - intake.source
  commands:
    - pip check
    - intake list --help
    - intake-server --help
  requires:
    - pip

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system
  dev_url: https://github.com/intake/intake
  doc_url: https://intake.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
