{% set version = "0.5.4" %}

package:
  name: intake
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake/intake-{{ version }}.tar.gz
  sha256: 81c3bdadbb81ec10c923b89e118c229d977a584ccbe27466f8fde41c0c274c3f

build:
  number: 0
  noarch: python
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - msgpack-python
    - msgpack-numpy
    - requests
    - tornado >=4.5.1
    - jinja2
    - ruamel.yaml >=0.15.0
    - dask >=2.2
    - python-snappy
    - appdirs
    - entrypoints
    # - holoviews
    # - ipywidgets >=7.2
    # - pandas

test:
  source_files:
    - intake
  imports:
    - intake
    - intake.auth
    - intake.auth.tests
    - intake.catalog
    - intake.catalog.tests
    - intake.cli
    - intake.cli.client
    - intake.cli.client.tests
    - intake.cli.server
    - intake.cli.server.tests
    - intake.container
    - intake.gui
    - intake.source
    - intake.source.tests
    - intake.tests
  commands:
    - intake list --help
    - intake-server --help

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Data load and catalog system

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
