{% set name = "intake" %}
{% set version = "2.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d3e82cba03e1659b094e3954143f453d54fd64328de322b2e4f11db5f9b1380

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
  run:
    - python
    - pyyaml
    - fsspec >=2023.0.0
    - platformdirs
    - networkx
    - packaging

test:
  imports:
    - intake
    - intake.catalog
    - intake.catalog.entry
    - intake.catalog.local
    - intake.container
    - intake.interface
    - intake.interface.catalog
    - intake.interface.source
    - intake.readers
    - intake.readers.catalogs
    - intake.readers.convert
    - intake.readers.datatypes
    - intake.readers.entry
    - intake.readers.importlist
    - intake.readers.metadata
    - intake.readers.mixins
    - intake.readers.namespaces
    - intake.readers.output
    - intake.readers.readers
    - intake.readers.search
    - intake.readers.transform
    - intake.readers.user_parameters
    - intake.source
    - intake.source.derived
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/intake/intake
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Data load and catalog system
  description: |
    Intake is a lightweight set of tools for loading and sharing data in data science projects. Intake helps you:
    * Load data from a variety of formats (see the current list of known plugins) into containers you already know, like Pandas dataframes, Python lists, NumPy arrays, and more.
    * Convert boilerplate data loading code into reusable Intake plugins.
    * Describe data sets in catalog files for easy reuse and sharing between projects and with others.
    * Share catalog information (and data sets) over the network with the Intake server.
  dev_url: https://github.com/intake/intake
  doc_url: https://intake.readthedocs.io/

extra:
  recipe-maintainers:
    - ocefpaf
    - martindurant
