travis:
  secure:
    BINSTAR_TOKEN: Vc0v94tz7rPl80imGSVtWOdB5LaD6iFWos6SveK9K8a+cUrtJyx6v9mSv37isCCC/oiqyFINcdJvX4MBVFkWunhD67MH91o5/NNAz6owZgvs/p/zEhWZMBBET1RYn5S/mS/T9NxqZinGmMBcOK5zE2S9ZmBQ8x7CCyfapXkp/bfX+5ufYAXunJaVVlkrqpfyh4WH7oyu+0/Q13XkqxEfGpeJHxMygGE/pHdYGP6GeYonllSwTlMInS/4hIN2EiNM1Wjzszw/J90hJ3y+rpW1H1k+GWHGDvFeIBLEzG2KBDix1fMTLlf9qOCSZUYIzMhBmNUts8Xk0Ksl2X8qhGY3qh0edYm2jLRgWPELOpdT2cBRJpCqRdwspOhoIrRL7qD2U9g1IZBgvSXmXu/JQrFwfwDa5QBX1Omh+W/L3k3XkJLU/vc+YeMcspURxttmGC4/N7gUrTsNIp84mXsjaVYX2bO7pGHbXC79o5qeOAV5SHu8TvMY03wuo0FqoMpNXc2evANm1Vw0FGVMktvALEzCEMsdXG29tBvyP6vq4EjDmbhlKVxOs9cBAdkCGEc1oM5y/u10/8FsJtDQyd135tSuh5lCB0xSTHwOeMHa93yLSzSATNByEhFrpcMuzPXvC8bUuZNk/0+Byzw3yqRKqKThtukwohPAw5z0/sFCkvND43w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
